### ISSUE TITLE
couldn't create the ViewHolder for message

### ISSUE THREAD

**Issue by luckscylla** [stfalcon-studio/ChatKit#104]
Hi 
I am trying to add user name to the incoming text message by using customized view holder.
However somehow it fail to create the message.
I also tried to remove all of the customized setting in the view holder, but it still fail.
BTW, there is no problem when I set customized layout only.
The code and error message are attached.
Could you please help to check is there anything wrong in my setting? Thanks in advance.

------------------------------- code -------------------------------
......
        MessageHolders holdersConfig = new MessageHolders()
                .setIncomingTextConfig(TextMessageViewHolder.class, R.layout.incoming_text_message);

        messagesAdapter = new MessagesListAdapter<>(user.getId(), holdersConfig, imageLoader);
        messagesList.setAdapter(messagesAdapter);
......
    public class TextMessageViewHolder extends MessageHolders.IncomingTextMessageViewHolder<Message> {
        private TextView nameView;
......
        public TextMessageViewHolder(View itemView) {
            super(itemView);
//            nameView = (TextView) itemView.findViewById(R.id.userName);
        }

        @Override
        public void onBind(Message message) {
            super.onBind(message);
//            nameView.setText(message.getUser().getName());
        }
    }

------------------------------- error message -------------------------------
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     java.lang.RuntimeException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
                                                                         at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:414)
                                                                         at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:398)
                                                                         at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:329)
                                                                         at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(MessagesListAdapter.java:98)
                                                                         at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(MessagesListAdapter.java:47)
                                                                         at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                         at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                         at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                         at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                         at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                         at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:570)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                         at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                         at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
                                                                         at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
                                                                         at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
                                                                         at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
                                                                         at android.view.View.layout(View.java:15697)
                                                                         at android.view.ViewGroup.layout(ViewGroup.java:5064)
                                                                         at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2232)
                                                                         at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1984)
                                                                         at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1163)
                                                                         at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6190)
                                                                         at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                                         at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                                         at android.view.Choreographer.doFrame(Choreographer.java:556)
                                                                         at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:159)
                                                                     	at android.app.ActivityThread.main(Ac

**Comment by DilbagSandhu** [comment]
if TextMessageViewHolder class is nested, make it static.

**Comment by luckscylla** [comment]
It works. Very appreciated ~

**Comment by luckscylla** [comment]
It works. Very appreciated ~

**Comment by ToGallop** [comment]
nice
