### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contentEquals(java.lang.CharSequence)' on a null object reference                                                                              at com.binrafiq.reborn.mvp.ui.image_detail.comment.MessageHolders.getViewType(MessageHolders.java:390)                                                                              at com.binrafiq.reborn.mvp.ui.image_detail.comment.MessagesAdapter.getItemViewType(MessagesAdapter.java:107)

### ISSUE THREAD

**Issue by chnouman** [stfalcon-studio/ChatKit#137]
Sometime it gives this error don't know why

**Comment by aana77** [comment]
Hey!
I am getting the same error. Were you able to solve this?
