### ISSUE TITLE
Custom dialog layout crash

### ISSUE THREAD

**Issue by aana77** [stfalcon-studio/ChatKit#194]
I am getting the following error

 java.lang.NullPointerException: Attempt to read from field 'android.view.View android.support.v7.widget.RecyclerView$ViewHolder.itemView' on a null object reference
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6795)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2685)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2394)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1559)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7358)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
        at android.view.Choreographer.doCallbacks(Choreographer.java:851)
        at android.view.Choreographer.doFrame(Choreographer.java:742)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

When running with default layout it works fine but with custom layout it crashes. 
I have taken the custom layout from the sample app layout, yet it is giving error.

**Comment by felipe10i9** [comment]
I have the same problem... Did you find a solution?

**Comment by felipe10i9** [comment]
I've ended up making my own adapter.
But thanks for your answer.
