### ISSUE TITLE
MessageInput Error. Is it a Bug of new version?

### ISSUE THREAD

**Issue by Dope-Cool** [stfalcon-studio/ChatKit#20]
Error log is 
      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myhouse.woohyun.tripal2/com.myhouse.woohyun.tripal2.DefaultMessagesActivity}: android.view.InflateException: Binary XML file line #25: Error inflating class com.stfalcon.chatkit.messages.MessageInput
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
                                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:170)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:146)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5635)
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                  at dalvik.system.NativeStart.main(Native Method)
                                                                               Caused by: android.view.InflateException: Binary XML file line #25: Error inflating class com.stfalcon.chatkit.messages.MessageInput
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:626)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                  at com.myhouse.woohyun.tripal2.DefaultMessagesActivity.onCreate(DefaultMessagesActivity.java:88)
                                                                                  at android.app.Activity.performCreate(Activity.java:5580)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:170) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5635) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.reflect.InvocationTargetException
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:600)
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                  at com.myhouse.woohyun.tripal2.DefaultMessagesActivity.onCreate(DefaultMessagesActivity.java:88) 
                                                                                  at android.app.Activity.performCreate(Activity.java:5580) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:170) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5635) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 
                                                                               Caused by: java.lang.NullPointerException
                                                                                  at com.stfalcon.chatkit.messages.MessageInput.init(MessageInput.java:201)
                                                                                  at com.stfalcon.chatkit.messages.MessageInput.init(MessageInput.java:151)
                                                                                  at com.stfalcon.chatkit.messages.MessageInput.<init>(MessageInput.java:58)
                                                                                  at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                  at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
                                                                                  at android.view.LayoutInflater.createView(LayoutInflater.java:600) 
                                                                                  at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702) 
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:761) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:498) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:398) 
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:354) 
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                  at com.myhouse.woohyun.tripal2.DefaultMessagesActivity.onCreate(DefaultMessagesActivity.java:88) 
                                                                                  at android.app.Activity.performCreate(Activity.java:5580) 
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400) 
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495) 
                                                                                  at android.app.ActivityThread.access$900(ActivityThread.java:170) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:146) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5635) 
                                                                                  at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                  at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
                                                                                  at dalvik.system.NativeStart.main(Native Method) 

And   at com.stfalcon.chatkit.messages.MessageInput.init(MessageInput.java:201) is
attachmentButton.setOnClickListener(this);

Is it a Bug of the new version of ChatKit?

**Comment by gab07** [comment]
Hi! Maybe this can help you for "android.view.InflateException: Binary XML file line ":

[http://stackoverflow.com/questions/19874882/android-view-inflateexception-binary-xml-file-error-inflating-class-fragment](url)

**Comment by troy379** [comment]
Hello @Dope-Cool 
I cannot reproduce this issue. Could you share more code please?

**Comment by lopezzbelgium** [comment]
I had the same issue and in my case it was app:inputButtonIcon being a vector

**Comment by pedrofsn** [comment]
I had the same issue, I just changed my messageinput id for something different of "messageInput" and it worked.

**Comment by lshannak** [comment]
same here, changing the messageinput id for something other than "messageInput" solved it, weird!
