### ISSUE TITLE
Crash when loading ViewHolder after Proguard added

### ISSUE THREAD

**Issue by xparabolax** [stfalcon-studio/ChatKit#210]
Error below only occurs if proguard enabled. I also have this in my proguard rules:
```
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$OutcomingTextMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$IncomingTextMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$IncomingImageMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$OutcomingImageMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
```

Issue is resolved if I keep all from ChatKit:
```
-keep class com.stfalcon.chatkit.** { *; }
```

```
2018-10-05 13:39:09.801 4266-4266/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.frogslayer.jobhub, PID: 4266
    java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
        at com.stfalcon.chatkit.messages.MessageHolders.a(:609)
        at com.stfalcon.chatkit.messages.MessageHolders.a(:512)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.c(:99)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.a(:47)
        at android.support.v7.widget.RecyclerView$a.b(:6685)
        at android.support.v7.widget.RecyclerView$p.a(:5869)
        at android.support.v7.widget.RecyclerView$p.a(:5752)
        at android.support.v7.widget.RecyclerView$p.c(:5748)
        at android.support.v7.widget.LinearLayoutManager$c.a(:2232)
        at android.support.v7.widget.LinearLayoutManager.a(:1559)
        at android.support.v7.widget.LinearLayoutManager.a(:1519)
        at android.support.v7.widget.LinearLayoutManager.a(:589)
        at android.support.v7.widget.RecyclerView.N(:3812)
        at android.support.v7.widget.RecyclerView.onMeasure(:3225)
        at android.view.View.measure(View.java:19883)
        at android.support.constraint.ConstraintLayout.a(:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(:1572)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19883)
        at android.support.constraint.ConstraintLayout.a(:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(:1572)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(:141)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6087)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
        at android.view.View.measure(View.java:19883)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2293)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1384)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1637)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1272)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by dennishylau** [comment]
Same thing happened to me, except `-keep class com.stfalcon.chatkit.** { *; } ` doesn't work either.

java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
        at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:640)
        at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:615)
        at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:556)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(SourceFile:99)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(SourceFile:47)
        at android.support.v7.widget.RecyclerView$a.createViewHolder(SourceFile:6794)
        at android.support.v7.widget.RecyclerView$p.a(SourceFile:5975)
        at android.support.v7.widget.RecyclerView$p.b(SourceFile:5858)
        at android.support.v7.widget.RecyclerView$p.d(SourceFile:5854)
        at android.support.v7.widget.LinearLayoutManager$c.a(SourceFile:2230)
        at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1557)
        at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1517)
        at android.support.v7.widget.LinearLayoutManager.e(SourceFile:587)
        at android.support.v7.widget.RecyclerView.B(SourceFile:3924)
        at android.support.v7.widget.RecyclerView.c(SourceFile:3641)
        at android.support.v7.widget.RecyclerView.onLayout(SourceFile:4194)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.support.design.widget.H.b(SourceFile:142)
        at android.support.design.widget.V.a(SourceFile:41)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.a(SourceFile:1556)
        at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:888)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.support.constraint.ConstraintLayout.onLayout(SourceFile:1915)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
        at android.view.View.layout(View.java:20699)
        at android.view.ViewGroup.layout(ViewGroup.java:6198)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2835)

**Comment by AbdullahUsmani** [comment]
> Same thing happened to me, except `-keep class com.stfalcon.chatkit.** { *; } ` doesn't work either.
> 
> java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
> at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:640)
> at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:615)
> at com.stfalcon.chatkit.messages.MessageHolders.a(SourceFile:556)
> at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(SourceFile:99)
> at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(SourceFile:47)
> at android.support.v7.widget.RecyclerView$a.createViewHolder(SourceFile:6794)
> at android.support.v7.widget.RecyclerView$p.a(SourceFile:5975)
> at android.support.v7.widget.RecyclerView$p.b(SourceFile:5858)
> at android.support.v7.widget.RecyclerView$p.d(SourceFile:5854)
> at android.support.v7.widget.LinearLayoutManager$c.a(SourceFile:2230)
> at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1557)
> at android.support.v7.widget.LinearLayoutManager.a(SourceFile:1517)
> at android.support.v7.widget.LinearLayoutManager.e(SourceFile:587)
> at android.support.v7.widget.RecyclerView.B(SourceFile:3924)
> at android.support.v7.widget.RecyclerView.c(SourceFile:3641)
> at android.support.v7.widget.RecyclerView.onLayout(SourceFile:4194)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.support.design.widget.H.b(SourceFile:142)
> at android.support.design.widget.V.a(SourceFile:41)
> at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.a(SourceFile:1556)
> at android.support.design.widget.CoordinatorLayout.onLayout(SourceFile:888)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.support.constraint.ConstraintLayout.onLayout(SourceFile:1915)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
> at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
> at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
> at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
> at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
> at android.view.View.layout(View.java:20699)
> at android.view.ViewGroup.layout(ViewGroup.java:6198)
> at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2835)

Did you implement custom view holders? If yes, did you try to keep their names from being obfuscated? I'll give this a try and update here.

**Comment by serkanucar** [comment]
You can use this proguard rules

-dontwarn com.stfalcon.**
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$OutcomingTextMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$IncomingTextMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$IncomingImageMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$OutcomingImageMessageViewHolder {
     public <init>(android.view.View, java.lang.Object);
     public <init>(android.view.View);
 }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$BaseMessageViewHolder {
      public <init>(android.view.View, java.lang.Object);
      public <init>(android.view.View);
}
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$BaseOutcomingMessageViewHolder {
      public <init>(android.view.View, java.lang.Object);
      public <init>(android.view.View);
  }
-keep class * extends com.stfalcon.chatkit.messages.MessageHolders$BaseIncomingMessageViewHolder {
       public <init>(android.view.View, java.lang.Object);
       public <init>(android.view.View);
}
