### ISSUE TITLE
Null pointer exception java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference at java.lang.String.contentEquals(String.java:1029)

### ISSUE THREAD

**Issue by aana77** [stfalcon-studio/ChatKit#221]
I am getting exception while setting adapter 

Here is the log: 

2018-11-04 19:55:23.413 15151-15151/com.jesentertainment.tokmay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jesentertainment.tokmay, PID: 15151
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.lang.String.contentEquals(String.java:1029)
        at com.stfalcon.chatkit.messages.MessageHolders.getViewType(MessageHolders.java:574)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.getItemViewType(MessagesListAdapter.java:120)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5926)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2685)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2394)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1559)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7358)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
        at android.view.Choreographer.doCallbacks(Choreographer.java:851)
        at android.view.Choreographer.doFrame(Choreographer.java:742)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
2018-11-04 19:55:23.414 15151-15151/com.jesentertainment.tokmay E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-11-04 19:55:23.415 15151-15151/com.jesentertainment.tokmay E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.jesentertainment.tokmay, PID: 15151
    java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at java.lang.String.contentEquals(String.java:1029)
        at com.stfalcon.chatkit.messages.MessageHolders.getViewType(MessageHolders.java:574)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.getItemViewType(MessagesListAdapter.java:120)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5926)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:587)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:762)
        at android.view.View.layout(View.java:19815)
        at android.view.ViewGroup.layout(ViewGroup.java:6084)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2685)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2394)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1559)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7358)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1039)
        at android.view.Choreographer.doCallbacks(Choreographer.java:851)
        at android.view.Choreographer.doFrame(Choreographer.java:742)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1025)
2018-11-04 19:55:23.416 15151-15151/com.jesentertainment.tokmay E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2018-11-04 19:55:23.417 598-598/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=15151 uid=10289 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0
2018-11-04 19:55:23.417 598-598/? E/SELinux: avc:  denied  { find } for service=opdiagnose pid=15151 uid=10289 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opdiagnose_service:s0 tclass=service_manager permissive=0

**Comment by aana77** [comment]
solved

**Comment by zaidmonis** [comment]
I'm getting the same error.
How'd you solved it?

**Comment by bradley-Amuj** [comment]
I experienced the same problem and solved it by making sure that the getter methods for the User model and Message model returned the appropriate variables  instead of leaving them as default null values
