### ISSUE TITLE
Runtime error with AndroidX

### ISSUE THREAD

**Issue by RegisSaffi** [stfalcon-studio/ChatKit#290]
java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
        at d.n.a.j.a.a(SourceFile:640)
        at d.n.a.j.a.a(SourceFile:615)
        at d.n.a.j.a.a(SourceFile:545)
        at d.n.a.j.c.onCreateViewHolder(SourceFile:99)
        at d.n.a.j.c.onCreateViewHolder(SourceFile:47)
        at androidx.recyclerview.widget.RecyclerView$g.createViewHolder(SourceFile:7069)
        at androidx.recyclerview.widget.RecyclerView$v.a(SourceFile:6233)
        at androidx.recyclerview.widget.RecyclerView$v.b(SourceFile:6116)
        at androidx.recyclerview.widget.RecyclerView$v.d(SourceFile:6112)
        at androidx.recyclerview.widget.LinearLayoutManager$c.a(SourceFile:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.a(SourceFile:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.c(SourceFile:640)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:4132)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:3849)
        at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:4402)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.b(SourceFile:1193)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.d(SourceFile:880)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:899)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:735)
        at android.view.View.layout(View.java:17545)
        at android.view.ViewGroup.layout(ViewGroup.java:5642)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2078)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1248)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6330)

**Comment by Andrew-Chen-Wang** [comment]
@RegisSaffi Any updates on this? Do you know where this could be a stem from? Or if you've used something else, any suggestions?

**Comment by TinaT2** [comment]
https://stackoverflow.com/questions/62846856/androidx-project-cant-recognize-the-class-of-library-using-android-support-v7/62850348#62850348

**Comment by Andrew-Chen-Wang** [comment]
@TinaT2 Based on the Traceback, it seems like OP is using AndroidX?
