### ISSUE TITLE
can't create view holder in minify enabled true

### ISSUE THREAD

**Issue by aliotadi** [stfalcon-studio/ChatKit#346]
i get this error when i run my builded app in production mode, i'm reporting this because you asked, i disabled the minify mode for now and eveything is working...

java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
        at c.f.a.b.b.a(Unknown Source:89)
        at c.f.a.b.b.b(Unknown Source:8)
        at c.f.a.b.g.d(:7)
        at androidx.recyclerview.widget.RecyclerView$s.k(:34)
        at androidx.recyclerview.widget.RecyclerView$s.e(:1)
        at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
        at androidx.recyclerview.widget.LinearLayoutManager.A1(Unknown Source:0)
        at androidx.recyclerview.widget.LinearLayoutManager.m1(:2)
        at androidx.recyclerview.widget.LinearLayoutManager.D0(:19)
        at androidx.recyclerview.widget.RecyclerView.r(Unknown Source:38)
        at androidx.recyclerview.widget.RecyclerView.p(:7)
        at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
        at android.view.View.layout(View.java:19659)
        at android.view.ViewGroup.layout(ViewGroup.java:6075)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NoSuchMethodException: <init> [class android.view.View]
        at java.lang.Class.getConstructor0(Class.java:2320)
        at java.lang.Class.getDeclaredConstructor(Class.java:2166)
        at c.f.a.b.b.a(Unknown Source:54)
        at c.f.a.b.b.b(Unknown Source:8) 
        at c.f.a.b.g.d(:7) 
        at androidx.recyclerview.widget.RecyclerView$s.k(:34) 
        at androidx.recyclerview.widget.RecyclerView$s.e(:1) 
        at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2) 
        at androidx.recyclerview.widget.LinearLayoutManager.A1(Unknown Source:0) 
        at androidx.recyclerview.widget.LinearLayoutManager.m1(:2) 
        at androidx.recyclerview.widget.LinearLayoutManager.D0(:19) 
        at androidx.recyclerview.widget.RecyclerView.r(Unknown Source:38) 
        at androidx.recyclerview.widget.RecyclerView.p(:7) 
        at androidx.recyclerview.widget.RecyclerView.onLayout(:2) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791) 
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635) 
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323) 
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261) 
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:761) 
        at android.view.View.layout(View.java:19659) 
        at android.view.ViewGroup.layout(ViewGroup.java:6075) 
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496) 
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212) 
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392) 
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:723) 
        at android.view.Choreographer.doFrame(Choreographer.java:658) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by akshay-nayak** [comment]
use the given progaurd rules
