### ISSUE TITLE
Unable to create custom holder

### ISSUE THREAD

**Issue by Damercy** [stfalcon-studio/ChatKit#353]
It says some unknown error has occured.

Here's the custom holder class:

```kotlin
class CustomMessageHolder(itemView: View, payload: Any): MessageHolders.IncomingTextMessageViewHolder<Message>(itemView,payload) {
    private var uploadDocsBtn: MaterialButton = itemView.findViewById(R.id.btnUploadDoc)

    override fun onBind(message: Message?) {
        super.onBind(message)
        val isDocumentTypeComment = message?.messagesTypes?.equals(DOCUMENT_UPLOAD_COMMENT)?:false
        if(isDocumentTypeComment)
            setupButtonListener(message?.messageText)
        else
            uploadDocsBtn.isVisible(false)
    }

    private fun setupButtonListener(messageText: String?) {
        uploadDocsBtn.setOnClickListener {
            Log.d(TAG, "setupButtonListener: Clicked")
        }
    }

}
```
Here's the stacktrace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.microfinance.lyt, PID: 13963
    java.lang.UnsupportedOperationException: Somehow we couldn't create the ViewHolder for message. Please, report this issue on GitHub with full stacktrace in description.
        at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:636)
        at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:611)
        at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:546)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(MessagesListAdapter.java:100)
        at com.stfalcon.chatkit.messages.MessagesListAdapter.onCreateViewHolder(MessagesListAdapter.java:48)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:640)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:784)
        at android.view.View.layout(View.java:22844)
        at android.view.ViewGroup.layout(ViewGroup.java:6389)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3470)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2938)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.stfalcon.chatkit.messages.MessageHolders.getHolder(MessageHolders.java:625)
        	... 58 more
     Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter payload
        at ai.microfinance.lyt.adapters.CustomMessageHolder.<init>(Unknown Source:7)
        	... 61 more
```

Would be grateful if somebody helps me out on this one!

**Comment by Damercy** [comment]
Found the mistake. I had to put payload's type as nullable in the constructor. Basically, change from:
```kotlin
class CustomMessageHolder(itemView: View, payload: Any): MessageHolders.IncomingTextMessageViewHolder<Message>(itemView,payload) {
    // Code
}
```
to
```kotlin
class CustomMessageHolder(itemView: View, payload: Any?): MessageHolders.IncomingTextMessageViewHolder<Message>(itemView,payload) {
    // Code
```
Notice the `?` in payload of type Any in the contructor.  

Closing the issue. Hope it helps somebody if they get stuck here. 😄
