### ISSUE TITLE
Custom View Holder throws java.lang.NoSuchMethodException <init> [class android.view.View]

### ISSUE THREAD

**Issue by maykelalien** [stfalcon-studio/ChatKit#45]
```
java.lang.NoSuchMethodException: <init> [class android.view.View]
    at java.lang.Class.getConstructorOrMethod(Class.java:472)
    at java.lang.Class.getDeclaredConstructor(Class.java:562)
    at com.stfalcon.chatkit.dialogs.DialogsListAdapter.onCreateViewHolder(DialogsListAdapter.java:113)
    at com.stfalcon.chatkit.dialogs.DialogsListAdapter.onCreateViewHolder(DialogsListAdapter.java:49)
    at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6367)
    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5555)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
    at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
    at android.support.design.widget.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:63)
    at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:135)
    at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
    at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
    at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
    at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1391)
    at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1548)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1457)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1548)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1457)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
    at android.view.View.layout(View.java:14878)
    at android.view.ViewGroup.layout(ViewGroup.java:4653)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2020)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1777)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1019)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5754)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5271)
    at java.lang.reflect.Method.invokeNative(Native Method)
```

I have followed the steps on creating a CustomViewHolder in your sample project but still getting this error.

here's my CustomViewHolder

```
public class CustomConversationDialogViewHolder extends DialogsListAdapter.DialogViewHolder<ChatUserConversationsEntity> {
    private ProgressBar progressBar;

    public CustomConversationDialogViewHolder(View itemView) {
        super(itemView);
        progressBar = (ProgressBar) itemView.findViewById(R.id.progress_bar);
    }

    @Override
    public void onBind(ChatUserConversationsEntity dialog) {
        if(dialog != null) {
            container.setVisibility(View.VISIBLE);
            progressBar.setVisibility(View.GONE);
            super.onBind(dialog);
            if (dialog.getLastMessage().getType() != null && dialog.getLastMessage().getType().equals(ChatMessagesEntity.I))
                tvLastMessage.setText(dialog.getLastMessage().getSender() + " sent a photo.");
            else if (dialog.getLastMessage().getType() != null && dialog.getLastMessage().getType().equals(ChatMessagesEntity.A))
                tvLastMessage.setText(dialog.getLastMessage().getSender() + " sent a link.");
        } else {
            container.setVisibility(View.INVISIBLE);
            progressBar.setVisibility(View.VISIBLE);
        }
    }
}
```

and here's how i implement into the adapter.

```
adapter = new DialogsListAdapter<>(R.layout.custom_item_dialog, CustomConversationDialogViewHolder.class, (imageView, url) -> {});
```

**Comment by hbmartin** [comment]
Is is possible that `CustomConversationDialogViewHolder` is an inner class?
If so you will need to declare it `static`

**Comment by atonamy** [comment]
@hbmartin this must be stated in the documentation to save time of developers when they searching how to resolve this crash
