### ISSUE TITLE
MessageListAdapter clear crashes no matter how I use it?

### ISSUE THREAD

**Issue by shusain93** [stfalcon-studio/ChatKit#48]
I've got a working demo on v1.2.0 and it's all good except now I want I need to clear the whole list and throw in new data. I'm calling this:
```
messagesListAdapter.clear();
setupMessages();
```

however whenever I call this I crash with the following if I tap anywhere in the scrollview
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.XXXXXXXX, PID: 13177
                                                                      java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{56e36af position=6 id=-1, oldPos=-1, pLpos:-1 no parent}
                                                                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                          at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:282)
                                                                          at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:336)
                                                                          at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:349)
                                                                          at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:356)
                                                                          at android.support.v7.widget.GapWorker.run(GapWorker.java:387)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

It's not an issue with setupMessages since clearing it doesn't actually seem to clear properly since everything is still in the MessageList view despite clearing. My guess at the issue is that clear works properly for the datasource held internally however this doesn't remove all the rows from the listview and so as it tries to draw them (touching the scrollview causes it to try to draw the cells out of view). I'm calling this all on UI thread. 

Do I need to somehow tell the `MessageList` to update?

**Comment by mradzinski** [comment]
As the error message says, you must notify the adapter of the underlying changes.

```
messagesListAdapter.clear();
messagesListAdapter.notifyDataSetChanged();
```

FYI: A quick Google search will give you this exact same answer.

**Comment by shusain93** [comment]
Ah man sorry. I did in fact search code `clear()` in the project but overlooked the notify call despite knowing that I was looking for just that. 

Thanks!
