### ISSUE TITLE
Online indicator - Null Pointer Exception

### ISSUE THREAD

**Issue by sciage** [stfalcon-studio/ChatKit#50]
I am trying to use custom viewholder to show if the user  is online or offline, but the app crashes everytime when it comes to checking the online indicator

Error takes me to this  code

if (dialog.getUsers().size() > 1) {
            onlineIndicator.setVisibility(View.GONE);
        } else {
            boolean isOnline = dialog.getUsers().get(0).isOnline();
            onlineIndicator.setVisibility(View.VISIBLE);
            if (isOnline) {
                onlineIndicator.setBackgroundResource(R.drawable.shape_bubble_online);
            } else {
                onlineIndicator.setBackgroundResource(R.drawable.shape_bubble_offline);
            }
        }

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean in.voiceme.app.voiceme.DTO.UserPojo.getIsOnline()' on a null object reference
                                                                          at in.voiceme.app.voiceme.chat.CustomDialogViewHolder.onBind(CustomDialogViewHolder.java:30)
                                                                          at in.voiceme.app.voiceme.chat.CustomDialogViewHolder.onBind(CustomDialogViewHolder.java:13)
                                                                          at com.stfalcon.chatkit.dialogs.DialogsListAdapter.onBindViewHolder(DialogsListAdapter.java:101)
                                                                          at com.stfalcon.chatkit.dialogs.DialogsListAdapter.onBindViewHolder(DialogsListAdapter.java:49)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.LinearLayout.setChildFrame(LinearLayout.java:2001)
                                                                          at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1844)
                                                                          at android.widget.LinearLayout.onLayout(LinearLayout.java:1753)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.widget.FrameLayout.layoutChildren(FrameLayout.java:396)
                                                                          at android.widget.FrameLayout.onLayout(FrameLayout.java:333)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2740)
                                                                          at android.view.View.layout(View.java:16953)
                                                                          at android.view.ViewGroup.layout(ViewGroup.java:5579)
                                                                          at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2562)
                                                                          at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2265)
                                                                      	at android.view.ViewRootImpl.doTraver

**Comment by mradzinski** [comment]
There's no such a thing as an online indicator built into ChatKit, so the issue must relay in your implementation rather than the library itself.

Furthermore, the error is stating that you have an uninitialized object, and just by reading the first line of that stacktrace I'm pretty sure it's `UserPojo`.

**Comment by troy379** [comment]
Yup, as @mradzinski said (thank you so much for such activity on this repo) it's looks like you have an null `UserPojo`'s object and the problem is in the following line:
```java
boolean isOnline = dialog.getUsers().get(0).isOnline();
```

Best regards, Alexander.
