### ISSUE TITLE
Crashing in below lollipop version

### ISSUE THREAD

**Issue by Hemant0601** [stfalcon-studio/ChatKit#95]
All the version below lollipop the application is crashing if Include your library while running app in DEBUG, its fine in release build but crashing  in DEBUG.
What happens ?
When I include your library , my IDE Android studio stops compiling JARS from libs folder due to which i get NoClassDefFoundError for all my libraries whichever comes first.

> `  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kochava/android/tracker/Feature$INPUTITEMS;
                                                                       at APP_ID.AppController.initKochava(AppController.java:222)
                                                                       at APP_ID.AppController.onCreate(AppController.java:212)
                                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1035)
                                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6041)
                                                                       at android.app.ActivityThread.access$1700(ActivityThread.java:211)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1766)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:145)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:6946)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.kochava.android.tracker.Feature$INPUTITEMS" on path: DexPathList[[`

Please help.

**Comment by bevzaanton** [comment]
Sorry but I think your issue not related to our library. If you still have problem please reopen this issue.
